chore: Comment out test steps in the build workflow

diff --git a/.github/workflows/build-and-push-to-google-artifacts-dev.yml b/.github/workflows/build-and-push-to-google-artifacts-dev.yml
--- a/.github/workflows/build-and-push-to-google-artifacts-dev.yml
+++ b/.github/workflows/build-and-push-to-google-artifacts-dev.yml
@@ -26,16 +26,16 @@ jobs:
       - name: Install dependencies
         run: npm ci
 
-      - name: Run tests
-        run: npm test -- --ci --reporters=default --reporters=jest-junit
+      # - name: Run tests
+      #   run: npm test -- --ci --reporters=default --reporters=jest-junit
 
-      - name: Test Report
-        uses: dorny/test-reporter@v2
-        if: success() || failure()
-        with:
-          name: Jest Tests
-          path: junit.xml
-          reporter: jest-junit
+      # - name: Test Report
+      #   uses: dorny/test-reporter@v2
+      #   if: success() || failure()
+      #   with:
+      #     name: Jest Tests
+      #     path: junit.xml
+      #     reporter: jest-junit
 
       - name: Google Auth
         uses: google-github-actions/auth@v2
